import 'package:freezed_annotation/freezed_annotation.dart';

part 'generated_recipe.freezed.dart';
part 'generated_recipe.g.dart';

/// A recipe generated by the AI.
/// This is the structured output from the Gemini API.
/// Can be reviewed and then saved as a regular Recipe.
@freezed
class GeneratedRecipe with _$GeneratedRecipe {
  const factory GeneratedRecipe({
    required String title,
    required String description,
    required int prepTimeMin,
    required int cookTimeMin,
    required int servings,
    required String difficulty,
    required String category,
    required List<GeneratedIngredient> ingredients,
    required List<String> steps,
    @Default([]) List<String> tags,
    @Default(false) bool isVegetarian,
    @Default(false) bool isVegan,
    String? mainVegetable,
    String? tip,
  }) = _GeneratedRecipe;

  factory GeneratedRecipe.fromJson(Map<String, dynamic> json) =>
      _$GeneratedRecipeFromJson(json);
}

/// An ingredient from an AI-generated recipe.
@freezed
class GeneratedIngredient with _$GeneratedIngredient {
  const factory GeneratedIngredient({
    required String item,
    required String amount,
    @Default('') String unit,
    String? note,
  }) = _GeneratedIngredient;

  factory GeneratedIngredient.fromJson(Map<String, dynamic> json) =>
      _$GeneratedIngredientFromJson(json);
}
