// Mocks generated by Mockito 5.4.6 from annotations
// in saisonier/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;

import 'package:http/http.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:pocketbase/src/auth_store.dart' as _i2;
import 'package:pocketbase/src/client.dart' as _i13;
import 'package:pocketbase/src/dtos/auth_methods_list.dart' as _i15;
import 'package:pocketbase/src/dtos/external_auth_model.dart' as _i21;
import 'package:pocketbase/src/dtos/jsonable.dart' as _i17;
import 'package:pocketbase/src/dtos/record_auth.dart' as _i16;
import 'package:pocketbase/src/dtos/record_model.dart' as _i14;
import 'package:pocketbase/src/dtos/result_list.dart' as _i18;
import 'package:pocketbase/src/services/admin_service.dart' as _i3;
import 'package:pocketbase/src/services/backup_service.dart' as _i10;
import 'package:pocketbase/src/services/collection_service.dart' as _i4;
import 'package:pocketbase/src/services/file_service.dart' as _i5;
import 'package:pocketbase/src/services/health_service.dart' as _i9;
import 'package:pocketbase/src/services/log_service.dart' as _i8;
import 'package:pocketbase/src/services/realtime_service.dart' as _i6;
import 'package:pocketbase/src/services/record_service.dart' as _i12;
import 'package:pocketbase/src/services/settings_service.dart' as _i7;
import 'package:saisonier/core/database/app_database.dart' as _i23;
import 'package:saisonier/features/seasonality/data/repositories/recipe_repository.dart'
    as _i24;
import 'package:saisonier/features/seasonality/data/repositories/vegetable_repository.dart'
    as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthStore_0 extends _i1.SmartFake implements _i2.AuthStore {
  _FakeAuthStore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdminService_1 extends _i1.SmartFake implements _i3.AdminService {
  _FakeAdminService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionService_2 extends _i1.SmartFake
    implements _i4.CollectionService {
  _FakeCollectionService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileService_3 extends _i1.SmartFake implements _i5.FileService {
  _FakeFileService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeService_4 extends _i1.SmartFake
    implements _i6.RealtimeService {
  _FakeRealtimeService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsService_5 extends _i1.SmartFake
    implements _i7.SettingsService {
  _FakeSettingsService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogService_6 extends _i1.SmartFake implements _i8.LogService {
  _FakeLogService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHealthService_7 extends _i1.SmartFake implements _i9.HealthService {
  _FakeHealthService_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupService_8 extends _i1.SmartFake implements _i10.BackupService {
  _FakeBackupService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_9 extends _i1.SmartFake implements _i11.Client {
  _FakeClient_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordService_10 extends _i1.SmartFake
    implements _i12.RecordService {
  _FakeRecordService_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_11 extends _i1.SmartFake implements Uri {
  _FakeUri_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePocketBase_12 extends _i1.SmartFake implements _i13.PocketBase {
  _FakePocketBase_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordModel_13 extends _i1.SmartFake implements _i14.RecordModel {
  _FakeRecordModel_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthMethodsList_14 extends _i1.SmartFake
    implements _i15.AuthMethodsList {
  _FakeAuthMethodsList_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordAuth_15 extends _i1.SmartFake implements _i16.RecordAuth {
  _FakeRecordAuth_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResultList_16<M extends _i17.Jsonable> extends _i1.SmartFake
    implements _i18.ResultList<M> {
  _FakeResultList_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PocketBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPocketBase extends _i1.Mock implements _i13.PocketBase {
  MockPocketBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get lang => (super.noSuchMethod(
        Invocation.getter(#lang),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.getter(#lang),
        ),
      ) as String);

  @override
  _i2.AuthStore get authStore => (super.noSuchMethod(
        Invocation.getter(#authStore),
        returnValue: _FakeAuthStore_0(
          this,
          Invocation.getter(#authStore),
        ),
      ) as _i2.AuthStore);

  @override
  _i3.AdminService get admins => (super.noSuchMethod(
        Invocation.getter(#admins),
        returnValue: _FakeAdminService_1(
          this,
          Invocation.getter(#admins),
        ),
      ) as _i3.AdminService);

  @override
  _i4.CollectionService get collections => (super.noSuchMethod(
        Invocation.getter(#collections),
        returnValue: _FakeCollectionService_2(
          this,
          Invocation.getter(#collections),
        ),
      ) as _i4.CollectionService);

  @override
  _i5.FileService get files => (super.noSuchMethod(
        Invocation.getter(#files),
        returnValue: _FakeFileService_3(
          this,
          Invocation.getter(#files),
        ),
      ) as _i5.FileService);

  @override
  _i6.RealtimeService get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeService_4(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i6.RealtimeService);

  @override
  _i7.SettingsService get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeSettingsService_5(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i7.SettingsService);

  @override
  _i8.LogService get logs => (super.noSuchMethod(
        Invocation.getter(#logs),
        returnValue: _FakeLogService_6(
          this,
          Invocation.getter(#logs),
        ),
      ) as _i8.LogService);

  @override
  _i9.HealthService get health => (super.noSuchMethod(
        Invocation.getter(#health),
        returnValue: _FakeHealthService_7(
          this,
          Invocation.getter(#health),
        ),
      ) as _i9.HealthService);

  @override
  _i10.BackupService get backups => (super.noSuchMethod(
        Invocation.getter(#backups),
        returnValue: _FakeBackupService_8(
          this,
          Invocation.getter(#backups),
        ),
      ) as _i10.BackupService);

  @override
  _i11.Client Function() get httpClientFactory => (super.noSuchMethod(
        Invocation.getter(#httpClientFactory),
        returnValue: () => _FakeClient_9(
          this,
          Invocation.getter(#httpClientFactory),
        ),
      ) as _i11.Client Function());

  @override
  set baseUrl(String? _baseUrl) => super.noSuchMethod(
        Invocation.setter(
          #baseUrl,
          _baseUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lang(String? _lang) => super.noSuchMethod(
        Invocation.setter(
          #lang,
          _lang,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authStore(_i2.AuthStore? _authStore) => super.noSuchMethod(
        Invocation.setter(
          #authStore,
          _authStore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set admins(_i3.AdminService? _admins) => super.noSuchMethod(
        Invocation.setter(
          #admins,
          _admins,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set collections(_i4.CollectionService? _collections) => super.noSuchMethod(
        Invocation.setter(
          #collections,
          _collections,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set files(_i5.FileService? _files) => super.noSuchMethod(
        Invocation.setter(
          #files,
          _files,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set realtime(_i6.RealtimeService? _realtime) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          _realtime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set settings(_i7.SettingsService? _settings) => super.noSuchMethod(
        Invocation.setter(
          #settings,
          _settings,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set logs(_i8.LogService? _logs) => super.noSuchMethod(
        Invocation.setter(
          #logs,
          _logs,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set health(_i9.HealthService? _health) => super.noSuchMethod(
        Invocation.setter(
          #health,
          _health,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set backups(_i10.BackupService? _backups) => super.noSuchMethod(
        Invocation.setter(
          #backups,
          _backups,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set httpClientFactory(_i11.Client Function()? _httpClientFactory) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientFactory,
          _httpClientFactory,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.RecordService collection(String? collectionIdOrName) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionIdOrName],
        ),
        returnValue: _FakeRecordService_10(
          this,
          Invocation.method(
            #collection,
            [collectionIdOrName],
          ),
        ),
      ) as _i12.RecordService);

  @override
  String filter(
    String? expr, [
    Map<String, dynamic>? query = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #filter,
          [
            expr,
            query,
          ],
        ),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.method(
            #filter,
            [
              expr,
              query,
            ],
          ),
        ),
      ) as String);

  @override
  Uri getFileUrl(
    _i14.RecordModel? record,
    String? filename, {
    String? thumb,
    String? token,
    Map<String, dynamic>? query = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileUrl,
          [
            record,
            filename,
          ],
          {
            #thumb: thumb,
            #token: token,
            #query: query,
          },
        ),
        returnValue: _FakeUri_11(
          this,
          Invocation.method(
            #getFileUrl,
            [
              record,
              filename,
            ],
            {
              #thumb: thumb,
              #token: token,
              #query: query,
            },
          ),
        ),
      ) as Uri);

  @override
  Uri buildUrl(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUrl,
          [
            path,
            queryParameters,
          ],
        ),
        returnValue: _FakeUri_11(
          this,
          Invocation.method(
            #buildUrl,
            [
              path,
              queryParameters,
            ],
          ),
        ),
      ) as Uri);

  @override
  _i20.Future<dynamic> send(
    String? path, {
    String? method = 'GET',
    Map<String, String>? headers = const {},
    Map<String, dynamic>? query = const {},
    Map<String, dynamic>? body = const {},
    List<_i11.MultipartFile>? files = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [path],
          {
            #method: method,
            #headers: headers,
            #query: query,
            #body: body,
            #files: files,
          },
        ),
        returnValue: _i20.Future<dynamic>.value(),
      ) as _i20.Future<dynamic>);
}

/// A class which mocks [RecordService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordService extends _i1.Mock implements _i12.RecordService {
  MockRecordService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseCollectionPath => (super.noSuchMethod(
        Invocation.getter(#baseCollectionPath),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.getter(#baseCollectionPath),
        ),
      ) as String);

  @override
  String get baseCrudPath => (super.noSuchMethod(
        Invocation.getter(#baseCrudPath),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.getter(#baseCrudPath),
        ),
      ) as String);

  @override
  _i13.PocketBase get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakePocketBase_12(
          this,
          Invocation.getter(#client),
        ),
      ) as _i13.PocketBase);

  @override
  _i14.RecordModel itemFactoryFunc(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #itemFactoryFunc,
          [json],
        ),
        returnValue: _FakeRecordModel_13(
          this,
          Invocation.method(
            #itemFactoryFunc,
            [json],
          ),
        ),
      ) as _i14.RecordModel);

  @override
  _i20.Future<_i6.UnsubscribeFunc> subscribe(
    String? topic,
    _i12.RecordSubscriptionFunc? callback, {
    String? expand,
    String? filter,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [
            topic,
            callback,
          ],
          {
            #expand: expand,
            #filter: filter,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<_i6.UnsubscribeFunc>.value(
            () => _i20.Future<void>.value()),
      ) as _i20.Future<_i6.UnsubscribeFunc>);

  @override
  _i20.Future<void> unsubscribe([String? topic = '']) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [topic],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<_i14.RecordModel> update(
    String? id, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    List<_i11.MultipartFile>? files = const [],
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [id],
          {
            #body: body,
            #query: query,
            #files: files,
            #headers: headers,
            #expand: expand,
            #fields: fields,
          },
        ),
        returnValue: _i20.Future<_i14.RecordModel>.value(_FakeRecordModel_13(
          this,
          Invocation.method(
            #update,
            [id],
            {
              #body: body,
              #query: query,
              #files: files,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
      ) as _i20.Future<_i14.RecordModel>);

  @override
  _i20.Future<void> delete(
    String? id, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<_i15.AuthMethodsList> listAuthMethods({
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAuthMethods,
          [],
          {
            #query: query,
            #headers: headers,
          },
        ),
        returnValue:
            _i20.Future<_i15.AuthMethodsList>.value(_FakeAuthMethodsList_14(
          this,
          Invocation.method(
            #listAuthMethods,
            [],
            {
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i20.Future<_i15.AuthMethodsList>);

  @override
  _i20.Future<_i16.RecordAuth> authWithPassword(
    String? usernameOrEmail,
    String? password, {
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithPassword,
          [
            usernameOrEmail,
            password,
          ],
          {
            #expand: expand,
            #fields: fields,
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<_i16.RecordAuth>.value(_FakeRecordAuth_15(
          this,
          Invocation.method(
            #authWithPassword,
            [
              usernameOrEmail,
              password,
            ],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i20.Future<_i16.RecordAuth>);

  @override
  _i20.Future<_i16.RecordAuth> authWithOAuth2Code(
    String? provider,
    String? code,
    String? codeVerifier,
    String? redirectUrl, {
    Map<String, dynamic>? createData = const {},
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithOAuth2Code,
          [
            provider,
            code,
            codeVerifier,
            redirectUrl,
          ],
          {
            #createData: createData,
            #body: body,
            #query: query,
            #headers: headers,
            #expand: expand,
            #fields: fields,
          },
        ),
        returnValue: _i20.Future<_i16.RecordAuth>.value(_FakeRecordAuth_15(
          this,
          Invocation.method(
            #authWithOAuth2Code,
            [
              provider,
              code,
              codeVerifier,
              redirectUrl,
            ],
            {
              #createData: createData,
              #body: body,
              #query: query,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
      ) as _i20.Future<_i16.RecordAuth>);

  @override
  _i20.Future<_i16.RecordAuth> authWithOAuth2(
    String? providerName,
    _i12.OAuth2UrlCallbackFunc? urlCallback, {
    List<String>? scopes = const [],
    Map<String, dynamic>? createData = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithOAuth2,
          [
            providerName,
            urlCallback,
          ],
          {
            #scopes: scopes,
            #createData: createData,
            #expand: expand,
            #fields: fields,
          },
        ),
        returnValue: _i20.Future<_i16.RecordAuth>.value(_FakeRecordAuth_15(
          this,
          Invocation.method(
            #authWithOAuth2,
            [
              providerName,
              urlCallback,
            ],
            {
              #scopes: scopes,
              #createData: createData,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
      ) as _i20.Future<_i16.RecordAuth>);

  @override
  _i20.Future<_i16.RecordAuth> authRefresh({
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authRefresh,
          [],
          {
            #expand: expand,
            #fields: fields,
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<_i16.RecordAuth>.value(_FakeRecordAuth_15(
          this,
          Invocation.method(
            #authRefresh,
            [],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i20.Future<_i16.RecordAuth>);

  @override
  _i20.Future<void> requestPasswordReset(
    String? email, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPasswordReset,
          [email],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> confirmPasswordReset(
    String? passwordResetToken,
    String? password,
    String? passwordConfirm, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPasswordReset,
          [
            passwordResetToken,
            password,
            passwordConfirm,
          ],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> requestVerification(
    String? email, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestVerification,
          [email],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> confirmVerification(
    String? verificationToken, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmVerification,
          [verificationToken],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> requestEmailChange(
    String? newEmail, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestEmailChange,
          [newEmail],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> confirmEmailChange(
    String? emailChangeToken,
    String? userPassword, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmEmailChange,
          [
            emailChangeToken,
            userPassword,
          ],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<List<_i21.ExternalAuthModel>> listExternalAuths(
    String? recordId, {
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listExternalAuths,
          [recordId],
          {
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<List<_i21.ExternalAuthModel>>.value(
            <_i21.ExternalAuthModel>[]),
      ) as _i20.Future<List<_i21.ExternalAuthModel>>);

  @override
  _i20.Future<void> unlinkExternalAuth(
    String? recordId,
    String? provider, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlinkExternalAuth,
          [
            recordId,
            provider,
          ],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<List<_i14.RecordModel>> getFullList({
    int? batch = 500,
    String? expand,
    String? filter,
    String? sort,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFullList,
          [],
          {
            #batch: batch,
            #expand: expand,
            #filter: filter,
            #sort: sort,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue:
            _i20.Future<List<_i14.RecordModel>>.value(<_i14.RecordModel>[]),
      ) as _i20.Future<List<_i14.RecordModel>>);

  @override
  _i20.Future<_i18.ResultList<_i14.RecordModel>> getList({
    int? page = 1,
    int? perPage = 30,
    bool? skipTotal = false,
    String? expand,
    String? filter,
    String? sort,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
          {
            #page: page,
            #perPage: perPage,
            #skipTotal: skipTotal,
            #expand: expand,
            #filter: filter,
            #sort: sort,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<_i18.ResultList<_i14.RecordModel>>.value(
            _FakeResultList_16<_i14.RecordModel>(
          this,
          Invocation.method(
            #getList,
            [],
            {
              #page: page,
              #perPage: perPage,
              #skipTotal: skipTotal,
              #expand: expand,
              #filter: filter,
              #sort: sort,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i20.Future<_i18.ResultList<_i14.RecordModel>>);

  @override
  _i20.Future<_i14.RecordModel> getOne(
    String? id, {
    String? expand,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOne,
          [id],
          {
            #expand: expand,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<_i14.RecordModel>.value(_FakeRecordModel_13(
          this,
          Invocation.method(
            #getOne,
            [id],
            {
              #expand: expand,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i20.Future<_i14.RecordModel>);

  @override
  _i20.Future<_i14.RecordModel> getFirstListItem(
    String? filter, {
    String? expand,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFirstListItem,
          [filter],
          {
            #expand: expand,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i20.Future<_i14.RecordModel>.value(_FakeRecordModel_13(
          this,
          Invocation.method(
            #getFirstListItem,
            [filter],
            {
              #expand: expand,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i20.Future<_i14.RecordModel>);

  @override
  _i20.Future<_i14.RecordModel> create({
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    List<_i11.MultipartFile>? files = const [],
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #body: body,
            #query: query,
            #files: files,
            #headers: headers,
            #expand: expand,
            #fields: fields,
          },
        ),
        returnValue: _i20.Future<_i14.RecordModel>.value(_FakeRecordModel_13(
          this,
          Invocation.method(
            #create,
            [],
            {
              #body: body,
              #query: query,
              #files: files,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
      ) as _i20.Future<_i14.RecordModel>);
}

/// A class which mocks [AuthStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStore extends _i1.Mock implements _i2.AuthStore {
  MockAuthStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get token => (super.noSuchMethod(
        Invocation.getter(#token),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.getter(#token),
        ),
      ) as String);

  @override
  _i20.Stream<_i2.AuthStoreEvent> get onChange => (super.noSuchMethod(
        Invocation.getter(#onChange),
        returnValue: _i20.Stream<_i2.AuthStoreEvent>.empty(),
      ) as _i20.Stream<_i2.AuthStoreEvent>);

  @override
  bool get isValid => (super.noSuchMethod(
        Invocation.getter(#isValid),
        returnValue: false,
      ) as bool);

  @override
  void save(
    String? newToken,
    dynamic newModel,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #save,
          [
            newToken,
            newModel,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VegetableRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVegetableRepository extends _i1.Mock
    implements _i22.VegetableRepository {
  MockVegetableRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Stream<List<_i23.Vegetable>> watchAll() => (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
        ),
        returnValue: _i20.Stream<List<_i23.Vegetable>>.empty(),
      ) as _i20.Stream<List<_i23.Vegetable>>);

  @override
  _i20.Stream<List<_i23.Vegetable>> watchFiltered(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchFiltered,
          [query],
        ),
        returnValue: _i20.Stream<List<_i23.Vegetable>>.empty(),
      ) as _i20.Stream<List<_i23.Vegetable>>);

  @override
  _i20.Stream<List<_i23.Vegetable>> watchSeasonal(int? month) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchSeasonal,
          [month],
        ),
        returnValue: _i20.Stream<List<_i23.Vegetable>>.empty(),
      ) as _i20.Stream<List<_i23.Vegetable>>);

  @override
  _i20.Future<void> toggleFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [id],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> sync() => (super.noSuchMethod(
        Invocation.method(
          #sync,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<List<String>> getFavoriteIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteIds,
          [],
        ),
        returnValue: _i20.Future<List<String>>.value(<String>[]),
      ) as _i20.Future<List<String>>);

  @override
  _i20.Future<void> setFavorite(
    String? id,
    bool? isFavorite,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFavorite,
          [
            id,
            isFavorite,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> clearAllFavorites() => (super.noSuchMethod(
        Invocation.method(
          #clearAllFavorites,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
}

/// A class which mocks [RecipeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeRepository extends _i1.Mock implements _i24.RecipeRepository {
  MockRecipeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Stream<List<_i23.Recipe>> watchRecipesForVegetable(
          String? vegetableId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipesForVegetable,
          [vegetableId],
        ),
        returnValue: _i20.Stream<List<_i23.Recipe>>.empty(),
      ) as _i20.Stream<List<_i23.Recipe>>);

  @override
  _i20.Stream<_i23.Recipe?> watchRecipe(String? id) => (super.noSuchMethod(
        Invocation.method(
          #watchRecipe,
          [id],
        ),
        returnValue: _i20.Stream<_i23.Recipe?>.empty(),
      ) as _i20.Stream<_i23.Recipe?>);

  @override
  _i20.Future<void> sync() => (super.noSuchMethod(
        Invocation.method(
          #sync,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
}
